### PR TITLE
Amal/fix/rel noopener locations templates

### PR DESCRIPTION
**Pull request by Cut3cumber**

### CODE REVIEW

**Review by slavanga — CHANGES_REQUESTED** [review]
Looks good. Please add the changelog entry.

**Comment by Cut3cumber** [comment]
@slavanga is this mew or fix?

**Comment by slavanga** [comment]
@Cut3cumber Let's list it under fix

**Comment by Cut3cumber** [comment]
@slavanga okay? :)

**Comment by slavanga** [comment]
@Cut3cumber there is a small typo but otherwise ok

**Review by slavanga — APPROVED** [review]

**Pull request merged**
