### PR TITLE
added hreflang links to sitemaps

### PR DESCRIPTION
**Pull request by kennydies**

### CODE REVIEW

**Review by tuerlefl — CHANGES_REQUESTED** [review]
please add some tests.

**Comment by tuerlefl** [comment]
this change requires manual changes on project level. could you please draft a CHANGELOG update as well.

**Comment by mariuskueng** [comment]
@tuerlefl @kennydies Will these changes be ready any time soon?

**Comment by tuerlefl** [comment]
I think so. we should add some tests first.

**Pull request merged**
